### ISSUE TITLE
`pytest-sugar` is not maintained? :thinking:

### ISSUE THREAD

**Issue by sisp** [samuelcolvin/pytest-pretty#3]
https://github.com/samuelcolvin/pytest-pretty/blob/0eb06ac11009224982aa68b0ac0759235b4fe8f9/README.md?plain=1#L10

Just wondering why you think `pytest-sugar` is not maintained:

* https://github.com/Teemu/pytest-sugar/commits/master
* https://github.com/Teemu/pytest-sugar/graphs/contributors

I have no insider information, but it looks maintained to me. :thinking:

**Comment by pawamoy** [comment]
I think I did see at some point a message stating it was unmaintained. I stopped using it, partially for this reason. Could be imagining things though.

In any case, good if it's being maintained [again]!

**Comment by samuelcolvin** [comment]
At the time I wrote this, I had reached out to the maintainer of pytest-sugar a few times and commented on https://github.com/Teemu/pytest-sugar/issues/224 offering to help, with no reply. Hence I assumed it wasn't maintained.

I'll remove this from the readme.

**Comment by sisp** [comment]
Ah, I hadn't seen that issue and the conversation there. For the said lack of interest by the current maintainers, it looks decently maintained. :smile: Thanks for the feedback and reference to that issue.

**Comment by samuelcolvin** [comment]
readme updated, 503f7d8a0f09062f59c22d01f2bc060b48912b09.
