### ISSUE TITLE
Add alternative for `pytester` fixture. 

### ISSUE THREAD

**Issue by Czaki** [samuelcolvin/pytest-pretty#7]
This plugin is really nice and really improves the readability of the output. But it breaks the `pytester` fixture https://docs.pytest.org/en/7.2.x/reference/reference.html#std-fixture-pytester 

The `pytester` is based on parsing pytest output to determine number of failed/passed/etc. 

We use the older version (testdir) in napari to validate if the fixture works correctly. 
https://github.com/napari/napari/blob/f5fcb7d2e3bb32950de227df61f7bc69846a6aa4/napari/_tests/test_pytest_plugin.py

So we cannot simply add pytest-pretty to our workflow.

**Comment by samuelcolvin** [comment]
Thanks for the issue, in concrete terms, what do you need from me here?

**Comment by Czaki** [comment]
> Thanks for the issue, in concrete terms, what do you need from me here?

are you open for such a feature in this package (maybe implemented by someone else)?

**Comment by samuelcolvin** [comment]
I think so, but I'm a bit lost on what it really does.

If it doesn't add massive complexity, or get in the way when not using it, happy to review a PR.

**Comment by Czaki** [comment]
> I think so, but I'm a bit lost on what it really does.

this fixture run test provides a string and pares output to check if it runs as expected. 



> If it doesn't add massive complexity, or get in the way when not using it, happy to review a PR.

I will try to do this.

**Comment by samuelcolvin** [comment]
Sounds good. Happy to review.
